/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalapp;

import java.awt.Toolkit;

/**
 *
 * @author windows
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        initUser();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth())/2, (Toolkit.getDefaultToolkit().getScreenSize().height - getHeight())/2 );
    }

    public void initUser(){
        menu_arbi.setEnabled(false);
        menu_user.setEnabled(false);
        menu_lap.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_user = new javax.swing.JMenuItem();
        menu_klien = new javax.swing.JMenuItem();
        menu_kend = new javax.swing.JMenuItem();
        menu_arbi = new javax.swing.JMenuItem();
        tutup = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        menu_trans = new javax.swing.JMenuItem();
        menu_lap = new javax.swing.JMenu();
        menu_laptrans = new javax.swing.JMenuItem();
        menu_lapklien = new javax.swing.JMenuItem();
        menu_lapken = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("RentalApp");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalapp/ic2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(153, 160));
        jLabel1.setMinimumSize(new java.awt.Dimension(153, 160));
        jLabel1.setPreferredSize(new java.awt.Dimension(153, 160));

        jMenu1.setText("File");

        menu_user.setText("Data Pengguna");
        menu_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_userActionPerformed(evt);
            }
        });
        jMenu1.add(menu_user);

        menu_klien.setText("Data Klien");
        menu_klien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_klienActionPerformed(evt);
            }
        });
        jMenu1.add(menu_klien);

        menu_kend.setText("Data Kendaraan");
        menu_kend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kendActionPerformed(evt);
            }
        });
        jMenu1.add(menu_kend);

        menu_arbi.setText("Data Area dan Biaya");
        menu_arbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_arbiActionPerformed(evt);
            }
        });
        jMenu1.add(menu_arbi);

        tutup.setText("Keluar");
        tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupActionPerformed(evt);
            }
        });
        jMenu1.add(tutup);

        jMenuBar1.add(jMenu1);

        transaksi.setText("Transaksi");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        menu_trans.setText("Rental");
        menu_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_transActionPerformed(evt);
            }
        });
        transaksi.add(menu_trans);

        jMenuBar1.add(transaksi);

        menu_lap.setText("Laporan");

        menu_laptrans.setText("Laporan Transaksi");
        menu_laptrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_laptransActionPerformed(evt);
            }
        });
        menu_lap.add(menu_laptrans);

        menu_lapklien.setText("Laporan Klien");
        menu_lapklien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_lapklienActionPerformed(evt);
            }
        });
        menu_lap.add(menu_lapklien);

        menu_lapken.setText("Laporan Kendaraan");
        menu_lapken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_lapkenActionPerformed(evt);
            }
        });
        menu_lap.add(menu_lapken);

        jMenuBar1.add(menu_lap);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_lapkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_lapkenActionPerformed
        // TODO add your handling code here:
        lapor_ken objLKen = new lapor_ken();
        objLKen.show();
    }//GEN-LAST:event_menu_lapkenActionPerformed

    private void tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupActionPerformed
        // TODO add your handling code here:
//        System.exit(0);
        dispose();
    }//GEN-LAST:event_tutupActionPerformed

    private void menu_klienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_klienActionPerformed
        // TODO add your handling code here:
        fmClient objClient = new fmClient(this, rootPaneCheckingEnabled);
        objClient.show();
    }//GEN-LAST:event_menu_klienActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiActionPerformed

    private void menu_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_transActionPerformed
        // TODO add your handling code here:
        fmTrans objTrans = new fmTrans(this, rootPaneCheckingEnabled);
        objTrans.show();
    }//GEN-LAST:event_menu_transActionPerformed

    private void menu_kendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_kendActionPerformed
        // TODO add your handling code here:
        fmKend objKend = new fmKend(this, rootPaneCheckingEnabled);
        objKend.show();
    }//GEN-LAST:event_menu_kendActionPerformed

    private void menu_arbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_arbiActionPerformed
        // TODO add your handling code here:
        fmArbi objArbi = new fmArbi(this, rootPaneCheckingEnabled);
        objArbi.show();
    }//GEN-LAST:event_menu_arbiActionPerformed

    private void menu_laptransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_laptransActionPerformed
        // TODO add your handling code here:
        lapor_tran objLTrans = new lapor_tran();
        objLTrans.setVisible(true);
    }//GEN-LAST:event_menu_laptransActionPerformed

    private void menu_lapklienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_lapklienActionPerformed
        // TODO add your handling code here:
        lapor_klien objLClient = new lapor_klien();
        objLClient.show();
    }//GEN-LAST:event_menu_lapklienActionPerformed

    private void menu_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_userActionPerformed
        // TODO add your handling code here:
        fmUser objfmUser = new fmUser(this, rootPaneCheckingEnabled);
        objfmUser.show();
    }//GEN-LAST:event_menu_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_arbi;
    private javax.swing.JMenuItem menu_kend;
    private javax.swing.JMenuItem menu_klien;
    private javax.swing.JMenu menu_lap;
    private javax.swing.JMenuItem menu_lapken;
    private javax.swing.JMenuItem menu_lapklien;
    private javax.swing.JMenuItem menu_laptrans;
    private javax.swing.JMenuItem menu_trans;
    private javax.swing.JMenuItem menu_user;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem tutup;
    // End of variables declaration//GEN-END:variables
}
